name: Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 00 * * 0'

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"
    
    - name: Build solution
      run: dotnet build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

  inspectcode:
    name: JB InspectCode
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"
    
    - name: Restore tools
      run: dotnet tool restore

    - name: Report results to Codacy
      run: |
        dotnet jb inspectcode CleanSolutionTemplate.sln --output=jb-inspectcode-report.xml --format=xml --build -a
        grep -q "<Issues />" report.xml || exit 1
