name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"./test-results/"

      - name: Merge tests with ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.20
        with:
          reports: "test-results/**/*.cobertura.xml"
          targetdir: "coverage-report"
          reporttypes: "Cobertura"
          verbosity: "Info"

      - name: Report results to Codacy
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage-report/Cobertura.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
