name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:15.3-alpine3.18
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      test-identity-server:
        image: fedeantuna/test-identity-server:v1.0.1
        ports:
          - 3210:80

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"./test-results/" --logger:"console;verbosity=detailed"

      - name: Merge tests with ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@abaac9fef72e4116bfc69905d51062790bda0335
        with:
          reports: "test-results/**/*.cobertura.xml"
          targetdir: "coverage-report"
          reporttypes: "Cobertura"
          verbosity: "Info"

      - name: Report results to Codacy
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage-report/Cobertura.xml
