name: Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Setup NuGet
        uses: nuget/setup-nuget@296fd3ccf8528660c91106efefe2364482f86d6f
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: "6.x"

      - name: Create the package
        run: nuget pack CleanSolutionTemplate.nuspec -NoDefaultExcludes

      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

      - name: Zip package
        run: |
          zip -j clean-solution-template.zip *.nupkg

      - name: Create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            clean-solution-template.zip
