name: Stryker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  RUNNING_FROM_PIPELINE: 'true'
  CURRENT_REPOSITORY_URL: $ {{ github.repositoryUrl }}
  STRYKER_DASHBOARD_BASELINE: ${{ github.base_ref }}
  STRYKER_DASHBOARD_VERSION: ${{ github.head_ref }}

jobs:
  stryker-mutation-report:
    name: Stryker Mutation Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Report
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: bash ${{ github.workspace }}/scripts/run_stryker.sh