name: Stryker

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
  STRYKER_EXPERIMENTAL: "false"
  STRYKER_MINIMUM_SCORE: "70"
  RUNNING_FROM_PIPELINE: "true"

jobs:
  stryker-mutation-report:
    name: Stryker Mutation Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Request - Generate Report
        if: github.event_name == 'pull_request'
        env:
          STRYKER_DASHBOARD_BASELINE: ${{ github.base_ref }}
          STRYKER_DASHBOARD_VERSION: ${{ github.head_ref }}
        run: bash ${{ github.workspace }}/scripts/run_stryker.sh

      - name: Merged - Generate Report
        if: github.event_name != 'pull_request'
        run: |
          echo "STRYKER_DASHBOARD_BASELINE=$(git branch --show-current)" >> $GITHUB_ENV
          echo "STRYKER_DASHBOARD_VERSION=$(git branch --show-current)" >> $GITHUB_ENV
          bash ${{ github.workspace }}/scripts/run_stryker.sh

      - name: Evaluating Mutation Score
        run: |
          STRYKER_SCORE=$(curl "https://badge-api.stryker-mutator.io/github.com/$CURRENT_REPOSITORY/$STRYKER_DASHBOARD_VERSION" -s | grep % | cut -d % -f 1 | rev | cut -d \" -f 1 | rev)
          echo "Minimum required score: $STRYKER_MINIMUM_SCORE"
          echo "Actual score: $STRYKER_SCORE"
          [[ $STRYKER_SCORE -ge $STRYKER_MINIMUM_SCORE ]] && exit 0 || exit 1
