name: Stryker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  RUNNING_FROM_PIPELINE: 'true'
  DOTNET_STRYKER_DASHBOARD_BASELINE: ${{ github.event.pull_request.base.sha }}
  DOTNET_STRYKER_DASHBOARD_VERSION: ${{ github.event.pull_request.head.sha }}

jobs:
  stryker-mutation-report:
    name: Stryker Mutation Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Report
        run: bash ./scripts/run_stryker.sh